name: Server CI

on:
  push:
    branches:
      - main
      - 'server/**'

jobs:
  server-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ajinjo/letschat:latest ./server

      - name: Push the Docker image to Docker Hub
        run: docker push ajinjo/letschat:latest
         
  # deploy-to-ec2:
  #   runs-on: ubuntu-latest
  #   needs: server-docker

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Install SSH
  #       run: sudo apt-get install openssh-client -y

  #     - name: Create .ssh directory
  #       run: mkdir -p ~/.ssh

  #     - name: Copy SSH private key
  #       run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

  #     - name: SSH into EC2 instance and deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.EC2_HOST }}
  #         username: ${{ secrets.EC2_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: ${{ secrets.EC2_SSH_PORT }}
  #         script: |
  #           cd /home/ubuntu/LetsChat/server
  #           sudo docker-compose pull app
  #           sudo docker-compose up -d